"""Fix amount and balance fields

Revision ID: 7b5d241ff4ee
Revises: 79b2758483f1
Create Date: 2024-10-27 13:57:40.511512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5d241ff4ee'
down_revision: Union[str, None] = '79b2758483f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # sqlite does not support altering columns, so we need to drop and recreate them
    op.drop_column('transfers', 'amount')
    op.drop_column('users', 'balance')
    op.add_column('transfers', sa.Column('amount', sa.REAL(precision=18, decimal_return_scale=2), nullable=False, default=0.0, server_default='0.0'))
    op.add_column('users', sa.Column('balance', sa.REAL(precision=18, decimal_return_scale=2), nullable=False, default=0.0, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'amount')
    op.drop_column('users', 'balance')
    op.add_column('transfers', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
